name: Build Windows EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package
      - name: Make EXE
        run: |
          Invoke-WebRequest -Uri "https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.11%2B9/OpenJDK17U-jre_x64_windows_hotspot_17.0.11_9.zip" -OutFile "jre.zip"
          Expand-Archive jre.zip -DestinationPath .
          Get-ChildItem -Directory | Where-Object { $_.Name -like "*jre*" } | Rename-Item -NewName "jre"
          echo "start jre\bin\javaw.exe -jar DebtManager.jar" > run.bat
          Compress-Archive -Path target\DebtManager.jar, jre, run.bat -DestinationPath DebtManager_Windows.zip
      - uses: actions/upload-artifact@v4
        with:
          name: Windows-软件包
          path: DebtManager_Windows.zip